#!/usr/bin/env bash































































echo "Done."git push -u origin mainecho "Pushing to remote. Ensure you have proper authentication (SSH key, git credential helper, or Personal Access Token)."# Push to remotefi  git remote add origin "$REMOTE_URL"else  fi    echo "Origin already set to target URL"  else    git remote add origin "$REMOTE_URL"    git remote remove origin    echo "Replacing existing origin remote URL"  if [ "$CURRENT_URL" != "$REMOTE_URL" ]; then  CURRENT_URL=$(git remote get-url origin)if git remote get-url origin >/dev/null 2>&1; then# Remove existing origin if it points elsewhereREMOTE_URL="https://github.com/Climb-Up-Tanzania/new_tag_and_seal_backend.git"# Configure remotegit branch -M main || true# Set main branchfi  git commit -m "first commit" || trueelse  echo "No changes to commit for README.md"if git diff --cached --quiet; then# Create a commit if there are staged changesgit add README.mdfi  touch README.md  echo "README.md not found. Creating an empty README.md"if [ ! -f README.md ]; then# Ensure README.md existsfi  echo "Initialized empty Git repository."  git initelse  echo ".git directory exists — skipping git init"if [ -d .git ]; thenfi  exit 1  echo "Git is not installed. Install git and try again." >&2else  echo "Git found."if command -v git >/dev/null 2>&1; thencd "$REPO_ROOT"REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"# Usage: chmod +x push_to_github.sh && ./push_to_github.sh# Helper script to push this repository to the specified GitHub remote.set -euo pipefail
